import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Themeprovider } from "@/components/theme-provider";
import Link from "next/link";
import { PokemonImage } from "@/components/ui/pokemon-image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Themeprovider attribute="class" defaultTheme="dark">

        <main className="flex min-h-screen flex-col items-center p-24">
          <div className="z-10 w-full max-w-5xl items-center justify-between text-sm lg:flex">
            <Link href="/"><h2 className="text-2xl text-bold">PokemonFinder</h2></Link>
          </div>
             {children}
        </main>

          
        </Themeprovider>
      </body>
    </html>
  );
}
